config/routes.rb
Rails.application.routes.draw do

  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create, :destroy]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:new, :create, :edit, :update]
  end

	resources :users, controller: "users", only: :show

  resources :addresses do 
    resources :listings, only: [:new, :create]
  end

  resources :listings, only: [:index, :edit, :show, :update, :destroy]

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:index, :edit, :show, :update, :destroy]

  resources :payments, only: [:new, :create]
	root 'welcome#index'
  get '/search', to: 'addresses#search'

  # get "/current_user/listings", to: "/users/:id/listing"

  get "/sign_in", to: "clearance/sessions#new"
  post "/sign_in", to: "clearance/sessions#create"
  delete "/sign_out", to: "clearance/sessions#destroy"

  get "/sign_up", to: "clearance/users#new"
  # post "/sign_up", to: "clearance/users#create"
  # get "users/show"

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # need to check out github for clearance how to generate routes here
  # root "users#index"


	#*** rails g clearance:routes show all these default Clearance routes
	# resources :passwords, controller: "clearance/passwords", only: [:create, :new]
	# resource :session, controller: "clearance/sessions", only: [:create]

	# resources :users, controller: "clearance/users", only: [:create] do
	#   resource :password,
	#     controller: "clearance/passwords",
	#     only: [:create, :edit, :update]
	# end

	# get "/sign_in" => "clearance/sessions#new", as: "sign_in"
	# delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
	# get "/sign_up" => "clearance/users#new", as: "sign_up"
	#*** end of default routes of Clearance
end

app/models/listing.rb
require 'carrierwave/orm/activerecord'

class Listing < ActiveRecord::Base
	validates :place_name, :place_type, :address, :bedroom, :bath, :amenity, :cost_per_night, :description, presence: true
	mount_uploaders :images, ImageUploader
	belongs_to :user
	belongs_to :address
	has_many :reservations, :dependent => :destroy
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_listing, only:[:show, :update, :destroy, :edit]
	
	def index
	  @listings = Listing.page(params[:page]).order('created_at DESC').per_page(2)
	end
	# def user
	# 	listings = Listing.where(user_id: current_user.id)
	# 	@listings = listings.order('id ASC')
	# end

	def new
		@listing = Listing.new
		@address = Address.find(params[:address_id])
	end

	def create
		@listing = Listing.new(listing_params)
		@listing.address_id = params[:address_id]
		@listing.user_id = current_user.id		
		if @listing.save
			redirect_to listings_path
		else
			# error_message
			render :new
		end
	end

	def edit
	end

	def update
		if @listing.update_attributes(listing_params)
			redirect_to listings_path
		else
			render 'edit'
		end
	end

	def destroy
    @listing.destroy
    redirect_to listings_path
	end

	private
	def listing_params	
		params.require(:listing).permit(:place_name, :place_type, :address_id, :bedroom, :bath, :amenity, :cost_per_night, :description, {images:[]})
	end

	def set_listing
		@listing = Listing.find(params[:id])
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.label :place_name %>
  <%= form.text_field :place_name %><br>

  <%= form.label :place_type %>
  <%= form.text_field :place_type %><br>

  <%= form.label :bedroom %>
  <%= form.select :bedroom, (1..10).to_a %><br>

  <%= form.label :bath %>
  <%= form.text_field :bath %><br>

  <%= form.label :amenity %>
  <%= form.text_field :amenity %><br>

  <%= form.label :cost_per_night %>
  <%= form.text_field :cost_per_night %><br>

  <%= form.label :description %>
  <%= form.text_field :description %><br>

  <%= form.file_field :images, multiple: true %>

</div>
<div class="submit-field">
  <%= form.submit %>
</div>

app/views/listings/edit.html.erb
<div id="clearance" class="">
  <h2><%= t(".title") %></h2>

  <%= form_for @listing do |form| %>
    <%= render partial: '/listings/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/listings/index.html.erb
<% if @listings[0].nil? %> 
	<h2> You have yet to list any property with us! </h2>
<% else %>

	<table class="table">
	<tr>
			<th> index </th>
			<th> place name </th>
			<th> place type </th>
			<th> address </th>
			<th> bedroom </th>
			<th> bath </th>
			<th> amenity </th>
			<th> cost per night </th>
			<th> description </th>
	</tr>

	<% @listings.each_with_index do |l, index| %>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= l.place_name %></td>
			<td><%= l.place_type %></td>
			<td><%= l.address.jalan %></td>
			<td><%= l.bedroom %></td>
			<td><%= l.bath %></td>
			<td><%= l.amenity %></td>
			<td><%= l.cost_per_night %></td>
			<td><%= l.description %></td>
			<td><%= link_to "view", "/listings/#{l.id}" %></td>
			<td><%= link_to "edit", "/listings/#{l.id}/edit" %></td>
			<td><%= link_to "delete", "/listings/#{l.id}", method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>

	</table>

<% end %>

<%= will_paginate %>

app/views/listings/new.html.erb
<div>
  <%= form_for @listing, url: address_listings_path(@address) do |form| %>
    <%= render partial: '/listings/form', object: form %>

  <% end %>
</div>

app/views/listings/show.html.erb
<% @listing.images.each do |i| %>
	<%= image_tag (i.medium.url) %><br>	
<% end %>

<%= "place name: #{@listing.place_name}" %></br>
<%= "place type: #{@listing.place_type}" %></br>
<%= "address: jalan #{@listing.address.jalan}, #{@listing.address.state}, #{@listing.address.country}" %></br>
<%= "bedroom: #{@listing.bedroom}" %></br>
<%= "bath: #{@listing.bath}" %></br>
<%= "amenity: #{@listing.amenity}" %></br>
<%= "cost per night: #{@listing.cost_per_night}" %></br>
<%= "description: #{@listing.description}" %></br>
<%= link_to "edit", "/listings/#{@listing.id}/edit" %></br>
<%= link_to "delete", "/listings/#{@listing.id}", method: :delete, data: {confirm: 'Are you sure?'} %><br>
<% if @listing.user_id != current_user.id %>
	<%= link_to "book it", new_listing_reservation_path(@listing) %>
<% end %>