config/routes.rb
Rails.application.routes.draw do

  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create, :destroy]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:new, :create, :edit, :update]
  end

	resources :users, controller: "users", only: :show

  resources :addresses do 
    resources :listings, only: [:new, :create]
  end

  resources :listings, only: [:index, :edit, :show, :update, :destroy]

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:index, :edit, :show, :update, :destroy]

  resources :payments, only: [:new, :create]
	root 'welcome#index'
  get '/search', to: 'addresses#search'

  # get "/current_user/listings", to: "/users/:id/listing"

  get "/sign_in", to: "clearance/sessions#new"
  post "/sign_in", to: "clearance/sessions#create"
  delete "/sign_out", to: "clearance/sessions#destroy"

  get "/sign_up", to: "clearance/users#new"
  # post "/sign_up", to: "clearance/users#create"
  # get "users/show"

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # need to check out github for clearance how to generate routes here
  # root "users#index"


	#*** rails g clearance:routes show all these default Clearance routes
	# resources :passwords, controller: "clearance/passwords", only: [:create, :new]
	# resource :session, controller: "clearance/sessions", only: [:create]

	# resources :users, controller: "clearance/users", only: [:create] do
	#   resource :password,
	#     controller: "clearance/passwords",
	#     only: [:create, :edit, :update]
	# end

	# get "/sign_in" => "clearance/sessions#new", as: "sign_in"
	# delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
	# get "/sign_up" => "clearance/users#new", as: "sign_up"
	#*** end of default routes of Clearance
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
	has_many :payments
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	
	def new
		@reservation = Reservation.new(listing_id: params[:listing_id])
		@listing = Listing.find(params[:listing_id])
	end

	def create
		a = start_date
		b = end_date
		@reservation = Reservation.new(start_date: a, end_date: b)
		@reservation.user_id = current_user.id
		@reservation.listing_id = params[:listing_id]		
		@host = "dicksonlyr@gmail.com"
		if @reservation.save
			# action mailer that will deliver straight?
			# ReservationMailer.notification_email(current_user.email, @host, @reservation.listing.id, @reservation.id).deliver_now
			
			# active job that will keep mails and perform later
	    ReservationJob.perform_later(current_user, @host, @reservation.listing.id, @reservation.id)
	    # call out reservation job to perform the mail sending task after @reservation is successfully saved
			redirect_to "/reservations/#{@reservation.id}"
		else
			
			# error_message
			render :new
		end
	end

	private
	def start_date	
		start_date_string = params[:reservation][:start_date]
		return start_date = datetify(start_date_string).to_date
		# byebug
	end

	def end_date
		end_date_string = params[:reservation][:end_date]
		return end_date = datetify(end_date_string).to_date
		# byebug
	end

	def datetify(date)
		mth = date[0..2]
		day = date[3..5]
		yr = date[6..9]
		day + mth + yr
	end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="text-field">
  <%= form.label :start_date %>
  <%= form.text_field :start_date, class:'datepicker' %><br>

  <%= form.label :end_date %>
  <%= form.text_field :end_date, class:'datepicker' %><br>

</div>
<div class="submit-field">
  <%= form.submit %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/reservations/new.html.erb
<div>
  <h2><%= t(".title") %></h2>
  
  <%= form_for @reservation, url: {action: "create"} do |form| %>
    <%= render partial: '/reservations/form', object: form %>

  <% end %>
</div>

app/views/reservations/show.html.erb
<% r = Reservation.find(params[:id]) %>
<%= "Your Booking: #{r.listing.place_name}" %><br>
<%= "Start Date: #{r.start_date}" %><br>
<%= "End Date: #{r.end_date}" %><br>

<ul class="list-group">
  <li class="list-group-item">
    <p>Listing name: <%= link_to r.listing.place_name, listing_path(r.listing) %></p>
    <p>Location: <%= r.listing.address.jalan %> </p>
    <p>Check-in Date: <%= r.start_date %></p>

    <p>Checkout Date: <%= r.end_date %></p>

    <strong>Payment Status:</strong>
      <% if r.payments.where(status: :authorized).count == 0%>
      <span class="btn btn-danger"> NOT PAID </span>

       <%= link_to 'Pay Now' , new_payment_path + "?id=" + r.id.to_s, class: "btn btn-warning"  %>
      <% else %>
      <span class="btn btn-success">PAID</span>
      <% end %>
  </li>
</ul>