config/routes.rb
Rails.application.routes.draw do

  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create, :destroy]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:new, :create, :edit, :update]
  end

	resources :users, controller: "users", only: :show

  resources :addresses do 
    resources :listings, only: [:new, :create]
  end

  resources :listings, only: [:index, :edit, :show, :update, :destroy]

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:index, :edit, :show, :update, :destroy]

  resources :payments, only: [:new, :create]
	root 'welcome#index'
  get '/search', to: 'addresses#search'

  # get "/current_user/listings", to: "/users/:id/listing"

  get "/sign_in", to: "clearance/sessions#new"
  post "/sign_in", to: "clearance/sessions#create"
  delete "/sign_out", to: "clearance/sessions#destroy"

  get "/sign_up", to: "clearance/users#new"
  # post "/sign_up", to: "clearance/users#create"
  # get "users/show"

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # need to check out github for clearance how to generate routes here
  # root "users#index"


	#*** rails g clearance:routes show all these default Clearance routes
	# resources :passwords, controller: "clearance/passwords", only: [:create, :new]
	# resource :session, controller: "clearance/sessions", only: [:create]

	# resources :users, controller: "clearance/users", only: [:create] do
	#   resource :password,
	#     controller: "clearance/passwords",
	#     only: [:create, :edit, :update]
	# end

	# get "/sign_in" => "clearance/sessions#new", as: "sign_in"
	# delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
	# get "/sign_up" => "clearance/users#new", as: "sign_up"
	#*** end of default routes of Clearance
end

app/views/layouts/_footer.html.erb
<div class="pusher">
  <div id="footer">
    <ul>
      <li><%= link_to "About Us", "/" %></li>
      <li><%= link_to "Privacy", "#" %></li>
      <li><%= link_to "Terms", "#" %></li>
      <li><%= link_to "Contact Us", "#" %></li>
      <li><%= link_to "Signup for newsletter", "#" %></li>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="menu">
  <ul class="active">
    <li class="current-item"><%= link_to "Home", root_url %></li>
    <% if !signed_in? %>
	    <li><%= link_to "Login", "/sign_in" %></li>
	    <li><%= link_to "Signup", "/sign_up" %></li>
    <%else%>
 			<li><%= link_to "log out" , sign_out_path ,method: :delete%></li>	
 			<li><%= link_to "list your property", new_address_path %></li>
 			<li><%= link_to "view your property", listings_path %></li>
		<% end %>
    <li><%= link_to "About Us", "/welcome/index" %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carebnb</title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
</head>
<body>

  <%= render partial: "layouts/navbar" %>

  <div class="container">
    <%= yield %>
  </div> 
  <%= render partial: "layouts/footer" %>

</body>
</html>